core_register:
    path:     /sign-up/
    defaults: { _controller: CoreBundle:Authentication:signUp }
    methods:  ['POST']

core_login:
    path:     /login/
    defaults: { _controller: CoreBundle:Authentication:login }
    methods:  ['POST']

core_logout:
    path:     /logout/
    defaults: { _controller: CoreBundle:Authentication:logout }

core_home:
    path:     /
    defaults: { _controller: CoreBundle:Home:home }
