core_register:
    path:     /signUp
    defaults: { _controller: CoreBundle:Authentication:signUp }
    methods:  ['POST']

core_login:
    path:     /login
    defaults: { _controller: CoreBundle:Authentication:login }
    methods:  ['POST']

core_logout:
    path:     /logout
    defaults: { _controller: CoreBundle:Authentication:logout }