core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

check_in:
    resource: "@CheckInBundle/Resources/config/routing.yml"
    prefix:   /vehicle/{license_plate_no}/check-in

fuel_fill_up:
    resource: "@FuelFillUpBundle/Resources/config/routing.yml"
    prefix:   /vehicle/{license_plate_no}/fuel-fill-up

misc_cost:
    resource: "@MiscCostBundle/Resources/config/routing.yml"
    prefix:   /vehicle/{license_plate_no}/misc-cost

vehicle:
    resource: "@VehicleBundle/Resources/config/routing.yml"
    prefix:   /vehicle

report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /report
