check_in:
    resource: "@CheckInBundle/Resources/config/routing.yml"
    prefix:   /check-in

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

fuel_fill_up:
    resource: "@FuelFillUpBundle/Resources/config/routing.yml"
    prefix:   /fuel-fill-up

misc_cost:
    resource: "@MiscCostBundle/Resources/config/routing.yml"
    prefix:   /misc-cost

vehicle:
    resource: "@VehicleBundle/Resources/config/routing.yml"
    prefix:   /vehicle
