# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    constants:
        class: CoreBundle\Utils\Constants\Retriever

    user_repo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
          - %entity.user%

    login_authenticator:
        class: CoreBundle\Utils\LoginAuthenticator
        arguments: ['@session', '@user_repo', '@constants']


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
