fuel_fill_up_get_all:
    path:     /
    defaults: { _controller: FuelFillUpBundle:View:getAll }
    methods:  ['GET']

fuel_fill_up_add:
    path:     /
    defaults: { _controller: FuelFillUpBundle:Manage:create }
    methods:  ['POST']

fuel_fill_up_get:
    path:     /{fuel_fill_up_id}/
    defaults: { _controller: FuelFillUpBundle:View:get }
    methods:  ['GET']

fuel_fill_up_update:
    path:     /{fuel_fill_up_id}/
    defaults: { _controller: FuelFillUpBundle:Manage:update }
    methods:  ['PUT']

fuel_fill_up_remove:
    path:     /{fuel_fill_up_id}/
    defaults: { _controller: FuelFillUpBundle:Manage:remove }
    methods:  ['DELETE']
