vehicle_get_all:
    path:     /
    defaults: { _controller: VehicleBundle:View:getAll }
    methods:  ['GET']

vehicle_add:
    path:     /
    defaults: { _controller: VehicleBundle:Manage:create }
    methods:  ['POST']

vehicle_get:
    path:     /{license_plate_no}/
    defaults: { _controller: VehicleBundle:View:get }
    methods:  ['GET']

vehicle_update:
    path:     /{license_plate_no}/
    defaults: { _controller: VehicleBundle:Manage:update }
    methods:  ['PUT']

vehicle_remove:
    path:     /{license_plate_no}/
    defaults: { _controller: VehicleBundle:Manage:remove }
    methods:  ['DELETE']

vehicle_driver_get_all:
    path:     /{license_plate_no}/driver/
    defaults: { _controller: VehicleBundle:Driver:getAll }
    methods:  ['GET']

vehicle_driver_add:
    path:     /{license_plate_no}/driver/{username}/
    defaults: { _controller: VehicleBundle:Driver:add }
    methods:  ['POST']

vehicle_driver_remove:
    path:     /{license_plate_no}/driver/{username}/
    defaults: { _controller: VehicleBundle:Driver:remove }
    methods:  ['DELETE']