vehicle_add:
    path:     /
    defaults: { _controller: VehicleBundle:Manage:createUpdate }
    methods:  ['POST']

vehicle_get_all:
    path:     /
    defaults: { _controller: VehicleBundle:View:getAll }
    methods:  ['GET']

vehicle_get:
    path:     /{license_plate_no}/
    defaults: { _controller: VehicleBundle:View:get }
    methods:  ['GET']

vehicle_update:
    path:     /{original_license_plate_no}/
    defaults: { _controller: VehicleBundle:Manage:createUpdate }
    methods:  ['PUT']

vehicle_delete:
    path:     /{license_plate_no}/
    defaults: { _controller: VehicleBundle:Manage:remove }
    methods:  ['DELETE']

vehicle_driver_add:
    path:     /{license_plate_no}/driver/{username}/
    defaults: { _controller: VehicleBundle:Driver:add }
    methods:  ['POST']

vehicle_driver_remove:
    path:     /{license_plate_no}/driver/{username}/
    defaults: { _controller: VehicleBundle:Driver:remove }
    methods:  ['DELETE']