check_in_get_all:
    path:     /
    defaults: { _controller: CheckInBundle:View:getAll }
    methods:  ['GET']

check_in_add:
    path:     /
    defaults: { _controller: CheckInBundle:Manage:create }
    methods:  ['POST']

check_in_get:
    path:     /{check_in_id}/
    defaults: { _controller: CheckInBundle:View:get }
    methods:  ['GET']

check_in_update:
    path:     /{check_in_id}/
    defaults: { _controller: CheckInBundle:Manage:update }
    methods:  ['PUT']

check_in_remove:
    path:     /{check_in_id}/
    defaults: { _controller: CheckInBundle:Manage:remove }
    methods:  ['DELETE']
