check_in_add:
    path:     /
    defaults: { _controller: CheckInBundle:Manage:createUpdate }
    methods:  ['POST']

check_in_update:
    path:     /{check_in_id}
    defaults: { _controller: CheckInBundle:Manage:createUpdate }
    methods:  ['PUT']